# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

podAnnotations:
  wave.pusher.com/update-on-config-change: "true"

service:
  name: gorush
  type: ClusterIP
  externalPort: 8088
  internalPort: 8088
  annotations: []
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
probePath: /
config_dir: /config/
certs_dir: /certificates
key: key_file
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1


certs:
  name: gorush-certs    

brand:
  default:
    ios:
      password: "Dresd3Ka-uBe!"
      key_file: "dkv-push.pem"
      voip:
        key_file: "dkv-voip-push.pem"
    android:
      api_key: "AAAA4SKa3Qo:APA91bFTRMA4mOpaNcLRfXEDMBRtqUmfHty9R0zBH7wLVygwbxs3fsIMwIqyULRziLyIteF9m0ITbM4x9Cs7Jez18nVplffs65kbwDjwDYNgSl0hjAos79MBh9grIV7CP29XlkHlU5Eb"
    web:
      api_key: "AAAA4SKa3Qo:APA91bFTRMA4mOpaNcLRfXEDMBRtqUmfHty9R0zBH7wLVygwbxs3fsIMwIqyULRziLyIteF9m0ITbM4x9Cs7Jez18nVplffs65kbwDjwDYNgSl0hjAos79MBh9grIV7CP29XlkHlU5Eb"
  